#!/bin/bash

xdotool key --window 41943074 --delay 50 v i Return
read -p 'Press enter to continue'
xdotool key --window 41943074 --delay 50 i h e l l o space h o w space a r e space y o u question space I space h o p e space y o u space a r e space h a v i n g space a space g r e a t space d a y exclam 0xff1b i space H E L L O space A G A I N , space I space M I S S E D space Y O U exclam Return
read -p 'Press enter to continue'
xdotool key --window 41943074 --delay 50 i 0x005c 0x005c 0x005c 0x005c 0x005c Return
read -p 'Press enter to continue'
xdotool key --window 41943074 --delay 50 